var lrdialog={_postion0:"_dialog20150529152603",_blackCover:null,_isIe6:(!-[1,]&&!window.XMLHttpRequest),coverbody:function(){var e=document.createElement("iframe");e.src="about:blank";e.width="100%";e.height="100%";e.frameborder=0;e.style.position="fixed";e.style.width="100%";e.style.height="100%";e.style.border=0;e.style.top=0;e.style.bottom=0;e.style.left=0;e.style.right=0;e.style.zIndex=1E5;e.style.filter="progid:DXImageTransform.Microsoft.Alpha(opacity:0)";var a=document.createElement("div");a.style.position="fixed";a.style.width=
"100%";a.style.height="100%";a.style.border=0;a.style.top=0;a.style.bottom=0;a.style.left=0;a.style.right=0;a.style.zIndex=100001;a.style.filter="alpha(opacity=40)";a.style.opacity=.4;a.style.background="#000000";this._isIe6&&(e.style.position="absolute",e.style.background="#cccccc",a.style.position="absolute",a.style.background="#cccccc");_blackCover.appendChild(e);_blackCover.appendChild(a)},show:function(e,a,c,f){document.body.style.overflow="hidden";document.body.parentNode.style.overflowY="hidden";
_blackCover=document.createElement("div");_blackCover.id=this._postion0;this.coverbody();var b,d;document.documentElement&&document.documentElement.clientHeight&&(b=document.documentElement.clientHeight,d=parseInt(b-f-39)/2);d=0>=d?0:d;b=parseInt(c);f=parseInt(f);var h=parseInt(c)/2;c=document.createElement("div");c.style.position="fixed";c.style.width=b+"px";c.style.top=parseInt(d)+"px";c.style.left="50%";c.style.marginLeft="-"+h+"px";c.style.zIndex=100002;c.style.overflow="hidden";c.style.zoom=
1;d=document.createElement("div");d.style.width="100%";d.style.height="34px";d.style.fontSize="14px";d.style.background="#101010";d.style.overflow="hidden";d.style.zoom=1;h=document.createElement("div");h.innerHTML=a;h.style.width="70%";h.style.height="34px";h.style.lineHeight="34px";h.style.styleFloat="left";h.style.cssFloat="left";h.style.textIndent="10px";h.style.color="#ffffff";h.style.overflow="hidden";h.style.zoom=1;a=document.createElement("div");a.style.width="34px";a.style.height="34px";
a.style.styleFloat="right";a.style.cssFloat="right";a.style.overflow="hidden";a.style.zoom=1;var g=document.createElement("a");g.setAttribute("onmouseover","this.style.color='#ffffff'");g.setAttribute("onmouseout","this.style.color='#428bca'");g.href="javascript:lrdialog.close(window);";g.innerHTML="\u00d7";g.style.height="34px";g.style.lineHeight="34px";g.style.fontSize="28px";g.style.fontFamily="\u5b8b\u4f53,\u65b0\u5b8b\u4f53";g.style.textDecoration="none";g.style.textAlign="center";g.style.verticalAlign=
"middle";g.style.display="block";g.style.cursor="pointer";g.style.color="#428bca";a.appendChild(g);d.appendChild(h);d.appendChild(a);a=document.createElement("div");a.style.width=b+"px";a.style.height=f+"px";a.style.background="#336699";b=document.createElement("iframe");b.setAttribute("frameborder",0);b.src=e;b.style.width="100%";b.style.height="100%";a.appendChild(b);c.appendChild(d);c.appendChild(a);this._isIe6&&(c.style.position="absolute");_blackCover.appendChild(c);document.body.insertBefore(_blackCover,
document.body.firstChild)},shownosize:function(e,a,c){var f=parseInt(c);document.body.style.overflow="hidden";document.body.parentNode.style.overflowY="hidden";_blackCover=document.createElement("div");_blackCover.id=this._postion0;this.coverbody();c=document.createElement("div");c.style.position="fixed";c.style.height="34px";c.style.top=f+"px";c.style.right=f+"px";c.style.left=f+"px";c.style.fontSize="14px";c.style.background="#101010";c.style.zIndex=100003;c.style.overflow="hidden";c.style.zoom=
1;var b=document.createElement("div");b.innerHTML=a;b.style.width="70%";b.style.height="34px";b.style.lineHeight="34px";b.style.styleFloat="left";b.style.cssFloat="left";b.style.textIndent="10px";b.style.color="#ffffff";b.style.overflow="hidden";b.style.zoom=1;a=document.createElement("div");a.style.width="34px";a.style.height="34px";a.style.styleFloat="right";a.style.cssFloat="right";a.style.overflow="hidden";a.style.zoom=1;var d=document.createElement("a");d.setAttribute("onmouseover","this.style.color='#ffffff'");
d.setAttribute("onmouseout","this.style.color='#428bca'");d.href="javascript:lrdialog.close(window);";d.innerHTML="\u00d7";d.style.height="34px";d.style.lineHeight="34px";d.style.fontSize="28px";d.style.fontFamily="\u5b8b\u4f53,\u65b0\u5b8b\u4f53";d.style.textDecoration="none";d.style.textAlign="center";d.style.verticalAlign="middle";d.style.display="block";d.style.cursor="pointer";d.style.color="#428bca";a.appendChild(d);c.appendChild(b);c.appendChild(a);b=document.createElement("div");b.style.position=
"fixed";b.style.top=f+34+"px";b.style.bottom=f+"px";b.style.left=f+"px";b.style.right=f+"px";b.style.background="#336699";b.style.zIndex=100003;b.style.overflow="hidden";b.style.zoom=1;f=document.createElement("iframe");f.setAttribute("frameborder",0);f.style.width="100%";f.style.height="100%";f.src=e;b.appendChild(f);this._isIe6&&(c.style.position="absolute",c.style.top=0,c.style.right=0,c.style.left=0,b.style.position="absolute",b.style.top="34px",b.style.bottom=0,b.style.left=0,b.style.right=0);
_blackCover.appendChild(c);_blackCover.appendChild(b);document.body.insertBefore(_blackCover,document.body.firstChild)},close:function(){var e=null;switch(arguments.length){case 0:e=parent;break;case 1:e=arguments[0]}e.document.body.removeChild(e.document.getElementById(this._postion0));e.document.body.style.overflow="";e.document.body.parentNode.style.overflowY=""}};